<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Room;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class RoomSeeder extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
      
        // $rooms = [
        //     ['room_number' => 101, 'room_type' => 'Deluxe Suite', 'price_per_night' => 270.00, 'availability' => 1, 'description' => 'Spacious deluxe suite with luxurious amenities.', 'image' => '../src/images/deluxe-suite.jpg', 'baths' => 1, 'area' => 50, 'guests' => 2, 'bathrooms' => 1, 'details' => 'This spacious suite features a king-sized bed, a private balcony, and a relaxing Jacuzzi. Guests will enjoy a modern design with plush furnishings. The suite is ideal for those seeking comfort and elegance during their stay. Perfect for a romantic getaway or a luxury vacation.'],
        //     ['room_number' => 102, 'room_type' => 'Standard Room', 'price_per_night' => 250.00, 'availability' => 1, 'description' => 'Comfortable standard room for business or leisure stays.', 'image' => '../src/images/standard-room.jpg', 'baths' => 1, 'area' => 30, 'guests' => 2, 'bathrooms' => 1, 'details' => 'This well-equipped standard room offers a queen-sized bed, a comfortable work desk, and modern amenities. It is perfect for business travelers or short stays. The room is designed for functionality and convenience, with a welcoming atmosphere that ensures a restful nights sleep. Enjoy a peaceful and productive stay.'],
        //     ['room_number' => 103, 'room_type' => 'Family Room', 'price_per_night' => 180.00, 'availability' => 1, 'description' => 'Family room with ample space and amenities for a family stay.', 'image' => '../src/images/family-room.jpg', 'baths' => 1, 'area' => 40, 'guests' => 4, 'bathrooms' => 1, 'details' => 'This family room is designed to accommodate up to four guests with two queen-sized beds. It includes a spacious living area, a large TV, and easy access to family-friendly facilities. Ideal for families looking to unwind and spend quality time together. The room offers a comfortable and homey feel that will make your stay memorable.'],
        //     ['room_number' => 104, 'room_type' => 'Presidential Suite', 'price_per_night' => 250.00, 'availability' => 1, 'description' => 'Exclusive presidential suite with stunning views.', 'image' => '../src/images/Penthouse-Suite.jpeg', 'baths' => 2, 'area' => 100, 'guests' => 4, 'bathrooms' => 2, 'details' => 'This prestigious suite features two luxurious bathrooms, a private office, and a spacious living room. Guests will experience unparalleled comfort and privacy with a large outdoor terrace offering panoramic views of the city. Designed for those who appreciate luxury, this suite includes premium services and exquisite details that elevate the experience. Perfect for high-profile guests.'],
        //     ['room_number' => 105, 'room_type' => 'Single Room', 'price_per_night' => 90.00, 'availability' => 1, 'description' => 'Compact room ideal for single travelers.', 'image' => '../src/images/single-room.webp', 'baths' => 1, 'area' => 20, 'guests' => 1, 'bathrooms' => 1, 'details' => 'This cozy room is designed with a single traveler in mind. It offers a comfortable bed, a work desk, and essential amenities for a short stay. The room is perfect for business trips or solo travelers seeking simplicity and comfort. Despite its compact size, it provides all the necessities to ensure a pleasant stay.'],
        //     ['room_number' => 106, 'room_type' => 'Double Room', 'price_per_night' => 140.00, 'availability' => 1, 'description' => 'A cozy room perfect for couples.', 'image' => '../src/images/double-room.jpg', 'baths' => 1, 'area' => 30, 'guests' => 2, 'bathrooms' => 1, 'details' => 'This double room features a queen-sized bed and a modern décor. It is designed for couples who want a peaceful retreat. The room includes amenities such as a flat-screen TV, Wi-Fi, and a mini-fridge. Guests will enjoy a serene atmosphere and great comfort. Its the ideal choice for a romantic getaway or weekend break.'],
        //     ['room_number' => 107, 'room_type' => 'Penthouse Suite', 'price_per_night' => 300.00, 'availability' => 1, 'description' => 'Luxurious penthouse suite with breathtaking views.', 'image' => '../src/images/Penthouse-Suite.jpeg', 'baths' => 3, 'area' => 150, 'guests' => 5, 'bathrooms' => 3, 'details' => 'The penthouse suite offers a sophisticated and elegant stay. It includes three spacious bedrooms, a private elevator, and a large living room. The suite is equipped with state-of-the-art technology and luxury amenities, such as a home theater system and a fully stocked minibar. The panoramic views from the terrace are stunning, making it the perfect accommodation for high-end guests.'],
        //     ['room_number' => 108, 'room_type' => 'Serene Standard Room', 'price_per_night' => 120.00, 'availability' => 1, 'description' => 'A peaceful room with a modern touch.', 'image' => '../src/images/standard_room_1.jpg', 'baths' => 1, 'area' => 30, 'guests' => 2, 'bathrooms' => 1, 'details' => 'This tranquil standard room is designed to provide a calm and relaxing environment. The room includes a queen-sized bed, a stylish bathroom, and modern furnishings. It is perfect for travelers looking for a comfortable yet affordable room to unwind. Guests will enjoy the bright and airy ambiance that enhances their stay.'],
        //     ['room_number' => 109, 'room_type' => 'Romantic Double Retreat', 'price_per_night' => 150.00, 'availability' => 1, 'description' => 'An intimate double room for romantic getaways.', 'image' => '../src/images/double-room-1.webp', 'baths' => 1, 'area' => 35, 'guests' => 2, 'bathrooms' => 1, 'details' => 'This romantic double room features a cozy atmosphere with a large king-sized bed, soft lighting, and plush furnishings. The room is perfect for couples seeking a relaxing escape. Enjoy the peaceful ambiance, ideal for intimate moments. Additional amenities include a minibar, a flat-screen TV, and a seating area to enhance your stay.'],
        //     ['room_number' => 110, 'room_type' => 'Prestige Suite', 'price_per_night' => 250.00, 'availability' => 1, 'description' => 'Elegantly designed suite with a touch of luxury.', 'image' => '../src/images/suite-room-1.jpg', 'baths' => 1, 'area' => 60, 'guests' => 2, 'bathrooms' => 1, 'details' => 'This suite combines elegance and comfort, featuring a king-sized bed, a spacious sitting area, and a stylish bathroom. The room is designed to cater to both business and leisure travelers. It includes premium amenities such as high-speed internet, a mini-fridge, and a coffee maker. The Prestige Suite offers the perfect combination of luxury and convenience for any guest.'],
        //     ['room_number' => 111, 'room_type' => 'Cozy Family Haven', 'price_per_night' => 180.00, 'availability' => 1, 'description' => 'Comfortable family room for a relaxing stay.', 'image' => '../src/images/family-room-1.jpg', 'baths' => 1, 'area' => 40, 'guests' => 4, 'bathrooms' => 1, 'details' => 'This family room features two queen-sized beds and a spacious area for everyone to feel comfortable. It also includes a separate seating area for relaxation and a large flat-screen TV. The room is perfect for families seeking comfort and ease, offering a homely atmosphere with all the necessary amenities. It ensures that all guests, including children, can enjoy their stay.'],
        //     ['room_number' => 112, 'room_type' => 'Family Comfort Retreat', 'price_per_night' => 200.00, 'availability' => 1, 'description' => 'A family-friendly room offering relaxation and comfort.', 'image' => '../src/images/family-room-2.jpg', 'baths' => 1, 'area' => 45, 'guests' => 4, 'bathrooms' => 1, 'details' => 'A spacious family room offering a comfortable stay for four people. The room includes two queen-sized beds and a cozy sitting area for relaxing. The room is designed for family vacations, with a playful atmosphere and easy access to all the hotels family-friendly facilities. Its a perfect choice for families who value comfort and relaxation.'],
        //     ['room_number' => 113, 'room_type' => 'Double Comfort Oasis', 'price_per_night' => 125.00, 'availability' => 1, 'description' => 'Comfortable and stylish room ideal for couples.', 'image' => '../src/images/double-room-2.jpg', 'baths' => 1, 'area' => 35, 'guests' => 2, 'bathrooms' => 1, 'details' => 'This double comfort room offers a stylish and relaxing environment for couples. It features a queen-sized bed, a small seating area, and modern amenities. The room is perfect for short getaways, offering everything you need for a comfortable and enjoyable stay. Guests will appreciate the tasteful décor and thoughtful touches that enhance the overall experience.'],
        //     ['room_number' => 114, 'room_type' => 'Opulent Suite Escape', 'price_per_night' => 280.00, 'availability' => 1, 'description' => 'Compact single room with essential amenities.', 'image' => '../src/images/suite-room-2.jpg', 'baths' => 1, 'area' => 20, 'guests' => 1, 'bathrooms' => 1, 'details' => 'This cozy single room is ideal for solo travelers. It features a comfortable single bed, a private bathroom, and a workspace. Perfect for short stays with all basic amenities to ensure a pleasant experience.'],
        //     ['room_number' => 115, 'room_type' => 'Standard Haven of Comfort', 'price_per_night' => 105.00, 'availability' => 1, 'description' => 'Spacious double room for two guests.', 'image' => '../src/images/standard_room_2.webp', 'baths' => 1, 'area' => 35, 'guests' => 2, 'bathrooms' => 1, 'details' => 'A comfortable room with a double bed, ideal for couples or friends. It includes a seating area, a work desk, and a modern bathroom. Guests will enjoy a relaxing and convenient stay.'],
        //     ['room_number' => 116, 'room_type' => 'The Family Getaway Nest', 'price_per_night' => 220.00, 'availability' => 1, 'description' => 'Room with two single beds.', 'image' => '../src/images/family-room-3.webp', 'baths' => 1, 'area' => 30, 'guests' => 2, 'bathrooms' => 1, 'details' => 'This twin room is designed for guests traveling together but requiring separate beds. It features two single beds, a private bathroom, and ample storage space. Perfect for friends or colleagues.'],
        //     ['room_number' => 117, 'room_type' => 'Luxury Double Delight', 'price_per_night' => 160.00, 'availability' => 1, 'description' => 'Luxurious room with deluxe amenities.', 'image' => '../src/images/double-room-3.jpg', 'baths' => 1, 'area' => 50, 'guests' => 2, 'bathrooms' => 1, 'details' => 'This deluxe room offers a king-sized bed, premium furnishings, and a spacious bathroom. Guests can enjoy a seating area, flat-screen TV, and other modern amenities for a luxurious stay.'],
        //     ['room_number' => 118, 'room_type' => 'Signature Suite Bliss', 'price_per_night' => 300.00, 'availability' => 1, 'description' => 'Spacious room for families.', 'image' => '../src/images/suite-room-3.webp', 'baths' => 1, 'area' => 70, 'guests' => 4, 'bathrooms' => 1, 'details' => 'This family room is perfect for parents with children. It features a king-sized bed, two single beds, and a large living area. With modern amenities and plenty of space, it ensures a comfortable family vacation.'],
        //     ['room_number' => 119, 'room_type' => 'Elegant Standard', 'price_per_night' => 130.00, 'availability' => 1, 'description' => 'Elegant suite with premium services.', 'image' => '../src/images/standard_room_3.jpg', 'baths' => 2, 'area' => 90, 'guests' => 3, 'bathrooms' => 2, 'details' => 'This elegant suite includes a spacious bedroom, a separate living area, and a luxurious bathroom. Designed for comfort, it offers premium services and stunning views. Ideal for extended stays.'],
        //     ['room_number' => 120, 'room_type' => 'Classic Family Suite', 'price_per_night' => 195.00, 'availability' => 1, 'description' => 'Luxurious room with a king-sized bed.', 'image' => '../src/images/family-room-4.jpeg', 'baths' => 1, 'area' => 60, 'guests' => 2, 'bathrooms' => 1, 'details' => 'This king room features a plush king-sized bed, a stylish bathroom, and modern decor. Guests will enjoy the spacious layout, cozy seating area, and excellent amenities for a relaxing stay.'],
        //     ['room_number' => 121, 'room_type' => 'Classic Double Serenity', 'price_per_night' => 135.00, 'availability' => 1, 'description' => 'Comfortable room with a queen-sized bed.', 'image' => '../src/images/double-room-4.webp', 'baths' => 1, 'area' => 55, 'guests' => 2, 'bathrooms' => 1, 'details' => 'This queen room is designed for comfort and relaxation. It features a queen-sized bed, a private bathroom, and a cozy seating area. Perfect for couples or solo travelers seeking a stylish space.'],
        //     ['room_number' => 122, 'room_type' => 'Elegant Suite Retreat', 'price_per_night' => 260.00, 'availability' => 1, 'description' => 'Ultimate luxury in a presidential suite.', 'image' => '../src/images/suite-room-4.jpg', 'baths' => 3, 'area' => 120, 'guests' => 6, 'bathrooms' => 3, 'details' => 'The presidential suite offers unparalleled luxury with a master bedroom, a spacious living room, and a private dining area. Guests will enjoy top-notch amenities, breathtaking views, and personalized services for an extraordinary stay.'],
        //     ['room_number' => 123,'roomType' => 'Luxe Standard Escape','price_per_night' => 140.00,'imageSrc' => '../src/images/standard_room_4.jpeg','availability' => 1,'description' => 'Indulge in a luxurious yet cozy retreat with our Luxe Standard Escape. Perfect for couples or solo travelers looking for comfort and elegance.','beds' => 1,'area' => 30,'guests' => 2,'bathrooms' => 1,'details' => 'Experience the ultimate blend of style and serenity in our Luxe Standard Escape. This room features a spacious 30 sqm layout, a plush king-size bed, and a private modern bathroom. Designed for up to two guests, it includes amenities like high-speed Wi-Fi, air conditioning, and a smart TV. Enjoy relaxing evenings or productive mornings in a space that feels just like home. With its serene ambiance and premium furnishings, it\'s the ideal choice for those who value luxury and comfort at an affordable price.']
        // ];

        // foreach ($rooms as $room) {
        //     DB::table('rooms')->updateOrInsert(
        //         ['room_number' => $room['room_number']], 
        //         $room 
        //     );
        // }
    }
}